name: Go
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup Go
        uses: actions/setup-go@v3

        with:
          go-version: '1.17.x'
      - name: Install dependencies
        run: go get all
      - name: Build mod download
        run: go mod download
      - name: Build mod vendor
        run: go mod vendor
        
 
  Veracode-SAST-Policy-Scan:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Archive Release
      uses: actions/setup-go@v3
      with:
        filename: 'veracode.zip'
        path: ./veracode.zip
  
              
    - uses: actions/upload-artifact@v2 
      with:
        path: ./veracode.zip
    - uses: veracode/veracode-uploadandscan-action@master 
      with:
        vid: '${{ secrets.VERACODE_ID }}'
        vkey: '${{ secrets.VERACODE_KEY }}'
        criticality: 'Medium'
        appname: 'Go Lang Dock'
        createprofile: 'true'
        filepath: 'veracode.zip'
        deleteIncompleteScan: 'true'
        version: ${{ github.run_id }}'
        scantimeout: 30
